
services:
  - type: web
    name: toy_app
    env: ruby
    buildCommand: |
      bundle install
      bundle install && bundle exec rake db:migrate
    startCommand: bundle exec rails db:migrate && bundle exec puma -C config/puma.rb
